#!/bin/bash
read -s -p "Database Password: " password
sudo apt-get install mysql-client mysql-server unzip apache2 php7.1 php7.1-mysql
sudo service apache2 restart
sudo rm -rf /var/www/html
sudo wget "https://wordpress.org/latest.zip" && sudo unzip latest.zip -d /var/www/
sudo mv /var/www/wordpress /var/www/html
sudo rm -rf latest.zip
(
cd /var/www/html
sudo chown www-data:www-data *
sudo chown www-data:www-data .*
)
mysql -u root -p$password -e "CREATE DATABASE wordpress;"
mysql -u root -p$password -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY '$password';"
mysql -u root -p$password -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost' IDENTIFIED BY '$password';"
mysql -u root -p$password -e "FLUSH PRIVILEGES;"


